version: "3.5"

services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=test
    restart: always
    networks:
      - backend
    ports:
      - 27017-27019:27017-27019

  backend:
    build: .
    image: avito-test-2
    container_name: backend
    environment:
      - PORT=80
      - DB_NAME=test
      - DB_PORT=27017
      - DB_HOST=mongo
    restart: always
    depends_on:
      - mongo
    networks:
      - backend
    ports:
      - 80:80

networks:
  backend:
    name: backend_network